<a href="https://colab.research.google.com/github/ilham-2326/FabricLens_370Project/blob/main/PreProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv("youtube_comments.csv")

In [6]:
df.head()

,author,updated_at,like_count,text,video_id,public
0,@joaquinrodriguezvillegas366,2026-02-25T00:49:20Z,0,This doesn't surprise me since the entire hist...,qpClEvsjW0s,True
1,@andrerosekriel1127,2026-02-22T11:15:55Z,0,Okay then why work for these factories.....or ...,qpClEvsjW0s,True
2,@RlxExplorer,2026-01-25T20:24:11Z,0,They fuel buying addiction. Same with Temu. No...,qpClEvsjW0s,True
3,@tishamonroe-0,2026-01-20T14:08:59Z,0,she holds her writing pen like a gorrilla,qpClEvsjW0s,True
4,@tishamonroe-0,2026-01-20T13:22:45Z,0,"SIMPLY. as the morality declines, the ability ...",qpClEvsjW0s,True

In [14]:

# remove comments where text is empty
df = df.dropna(subset=['text'])
# lower case it
df["text"] = df["text"].str.islower()

#  Remove punctuation/special chars


# tokenize



# stemming

/tmp/ipykernel_1435/2476599410.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text"] = df["text"].str.islower()

In [15]:
df.shape

(10505, 6)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10505 entries, 0 to 10510
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   author      10505 non-null  object
 1   updated_at  10505 non-null  object
 2   like_count  10505 non-null  int64
 3   text        10505 non-null  bool
 4   video_id    10505 non-null  object
 5   public      10505 non-null  bool
dtypes: bool(2), int64(1), object(3)
memory usage: 430.9+ KB

In [17]:
df.isnull().sum()

author        0
updated_at    0
like_count    0
text          0
video_id      0
public        0
dtype: int64

In [26]:
df.duplicated().sum()

np.int64(4)

In [ ]:
# make sure all comments are in english
# perform EDA
# make it into a csv file or json file / or you can publish in github or hugging face
#